
import java.awt.Image;
import javax.swing.ImageIcon;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Alpro2 extends javax.swing.JFrame {
    ArrayList course = new ArrayList();
    ArrayList sks = new ArrayList();
    ArrayList abs = new ArrayList();
    
    DefaultTableModel dataModel;
    
    private ImageIcon resizeImage(String path, int x, int y){
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        Image img = icon.getImage();
        Image resizeImg = img.getScaledInstance(x, y, Image.SCALE_SMOOTH);
        ImageIcon finalIcon = new ImageIcon(resizeImg);
        return finalIcon;
    }
    /**
     * Creates new form Alpro2
     */
    public Alpro2() {
        initComponents();
        lblHome.setIcon(resizeImage("/img/Home.png", 260, 450));
        lblManage.setIcon(resizeImage("/img/Manage.png", 260, 450));
        lblSession.setIcon(resizeImage("/img/Session.png", 260, 450));
        panelLogin.setVisible(true);
        panelHome.setVisible(false);
        panelManage.setVisible(false);
        panelSession.setVisible(false);
        panelAdd.setVisible(false);
        panelRemove.setVisible(false);
        panelAbsence.setVisible(false);
        panelShow.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        panelManage = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblManage = new javax.swing.JLabel();
        panelSession = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblSession = new javax.swing.JLabel();
        panelRemove = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        removeField = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panelAdd = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldCourse = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        sksCourse = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        panelAbsence = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        comboMatkul = new javax.swing.JComboBox();
        absentButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelShow = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        panelLogin = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        panelHome.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 130, 450));

        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        panelHome.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 130, 440));

        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home.png"))); // NOI18N
        panelHome.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 450));

        panelManage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        panelManage.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        panelManage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 220));

        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        panelManage.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 224, 260, 230));

        lblManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Manage.png"))); // NOI18N
        panelManage.add(lblManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 450));

        panelSession.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        panelSession.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        panelSession.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 230));

        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        panelSession.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 224, 260, 230));

        lblSession.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Session.png"))); // NOI18N
        panelSession.add(lblSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 450));

        panelRemove.setBackground(new java.awt.Color(255, 51, 51));
        panelRemove.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Back");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        panelRemove.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Remove a Course");
        panelRemove.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        removeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFieldActionPerformed(evt);
            }
        });
        panelRemove.add(removeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 150, -1));

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        panelRemove.add(removeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRemove.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 30));

        panelAdd.setBackground(new java.awt.Color(255, 51, 51));
        panelAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Back");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        panelAdd.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add A Course");
        jLabel5.setToolTipText("");
        panelAdd.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 100, 40));

        fieldCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCourseActionPerformed(evt);
            }
        });
        panelAdd.add(fieldCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 150, -1));

        jLabel6.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name");
        panelAdd.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SKS");
        panelAdd.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        panelAdd.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 60, -1));

        sksCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih SKS...", "2", "3", "4" }));
        panelAdd.add(sksCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelAdd.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, 20));

        panelAbsence.setBackground(new java.awt.Color(255, 51, 51));
        panelAbsence.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Back");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        panelAbsence.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Mata Kuliah");
        panelAbsence.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        comboMatkul.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelAbsence.add(comboMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        absentButton.setText("Absent");
        panelAbsence.add(absentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel16.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Lets Absence");
        panelAbsence.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelAbsence.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 20));

        panelShow.setBackground(new java.awt.Color(255, 51, 51));
        panelShow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("SHOW ABSENCE");
        panelShow.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Back");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        panelShow.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 40, 30));

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelData);

        panelShow.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 290, 190));

        panelLogin.setBackground(new java.awt.Color(255, 51, 51));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("User");
        panelLogin.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Pass");
        panelLogin.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });
        panelLogin.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 150, -1));
        panelLogin.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 150, -1));

        jLabel22.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ABSENCE");
        panelLogin.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 100, -1));

        jLabel23.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("REMINDER");
        panelLogin.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel24.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("LOGIN");
        panelLogin.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        panelLogin.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 24, Short.MAX_VALUE)
                    .addComponent(panelAbsence, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addGap(0, 26, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelShow, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 125, Short.MAX_VALUE)
                    .addComponent(panelAbsence, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addGap(0, 125, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelShow, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        panelHome.setVisible(false);
        panelManage.setVisible(true);
        panelSession.setVisible(false);
        panelAdd.setVisible(false);
        panelRemove.setVisible(false);
        panelAbsence.setVisible(false);
        panelShow.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        panelHome.setVisible(false);
        panelManage.setVisible(false);
        panelSession.setVisible(true);
        panelAdd.setVisible(false);
        panelRemove.setVisible(false);
        panelAbsence.setVisible(false);
        panelShow.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        panelHome.setVisible(true);
        panelManage.setVisible(false);
        panelSession.setVisible(false);
        panelAdd.setVisible(false);
        panelRemove.setVisible(false);
        panelAbsence.setVisible(false);
        panelShow.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        panelHome.setVisible(false);
        panelManage.setVisible(true);
        panelSession.setVisible(false);
        panelAdd.setVisible(false);
        panelRemove.setVisible(false);
        panelAbsence.setVisible(false);
        panelShow.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void fieldCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCourseActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String[] column = {"Nama", "SKS"};
        dataModel = new DefaultTableModel(column, 0);
        course.add(fieldCourse.getText());
        sks.add(sksCourse.getSelectedItem());
        
        for(int i = 0; i < course.size(); i++) {
            String[] toTabel = {String.valueOf(course.get(i)), String.valueOf(sks.get(i))};
            dataModel.addRow(toTabel);
        }
        
        
        
        tabelData.setModel(dataModel);
    }//GEN-LAST:event_addButtonActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        panelHome.setVisible(false);
        panelManage.setVisible(false);
        panelSession.setVisible(false);
        panelAdd.setVisible(true);
        panelRemove.setVisible(false);
        panelAbsence.setVisible(false);
        panelShow.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        panelHome.setVisible(false);
        panelManage.setVisible(false);
        panelSession.setVisible(true);
        panelAdd.setVisible(false);
        panelRemove.setVisible(false);
        panelAbsence.setVisible(false);
        panelShow.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void removeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeFieldActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        panelHome.setVisible(false);
        panelManage.setVisible(false);
        panelSession.setVisible(false);
        panelAdd.setVisible(false);
        panelRemove.setVisible(true);
        panelAbsence.setVisible(false);
        panelShow.setVisible(false);// TODO add your handling code here:
        
        
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        panelHome.setVisible(false);
        panelManage.setVisible(false);
        panelSession.setVisible(true);
        panelAdd.setVisible(false);
        panelRemove.setVisible(false);
        panelAbsence.setVisible(false);
        panelShow.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        panelHome.setVisible(false);
        panelManage.setVisible(false);
        panelSession.setVisible(false);
        panelAdd.setVisible(false);
        panelRemove.setVisible(false);
        panelAbsence.setVisible(true);
        panelShow.setVisible(false);// TODO add your handling code here:
        
        String[] comboModel = new String[course.size()];
        System.out.println(course.size());
        
        for (int i = 0; i < course.size(); i++) {
            comboModel[i] = String.valueOf(course.get(i));
            System.out.println("nilai = " + String.valueOf(course.get(i)));
        }
        
        comboMatkul.setModel(new javax.swing.DefaultComboBoxModel(comboModel));
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        panelHome.setVisible(false);
        panelManage.setVisible(false);
        panelSession.setVisible(true);
        panelAdd.setVisible(false);
        panelRemove.setVisible(false);
        panelAbsence.setVisible(false);
        panelShow.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        panelHome.setVisible(false);
        panelManage.setVisible(false);
        panelSession.setVisible(false);
        panelAdd.setVisible(false);
        panelRemove.setVisible(false);
        panelAbsence.setVisible(false);
        panelShow.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        panelHome.setVisible(true);
        panelManage.setVisible(false);
        panelSession.setVisible(false);
        panelAdd.setVisible(false);
        panelRemove.setVisible(false);
        panelAbsence.setVisible(false);
        panelShow.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
       int index = course.indexOf(removeField.getText());
        System.out.println(index);
        if(index < 0) {
            System.out.println("tidak ditemukan data"); 
        } else {
            course.remove(index);
            sks.remove(index);
        }
       
        for(int j = tabelData.getRowCount() - 1; j > 0; j--) {
            dataModel.removeRow(j);
        }
        
        
       for(int i = 0; i < course.size(); i++) {
            String[] toTabel = {String.valueOf(course.get(i)), String.valueOf(sks.get(i))};
            dataModel.addRow(toTabel);
        }
       
       
    }//GEN-LAST:event_removeButtonActionPerformed

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String User = "admin";
        String Pass = "1234";
        String cUser = userField.getText();
        String cPass = String.valueOf(passField.getPassword());
        
        if((cUser.compareTo(User)==0)&&(cPass.compareTo(Pass)==0)){
            panelHome.setVisible(true);
            panelManage.setVisible(false);
            panelSession.setVisible(false);
            panelAdd.setVisible(false);
            panelRemove.setVisible(false);
            panelAbsence.setVisible(false);
            panelShow.setVisible(false);
            panelLogin.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "User atau Passwor Anda salah");
            userField.setText("");
            passField.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alpro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alpro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alpro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alpro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alpro2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton absentButton;
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox comboMatkul;
    private javax.swing.JTextField fieldCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblManage;
    private javax.swing.JLabel lblSession;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel panelAbsence;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelManage;
    private javax.swing.JPanel panelRemove;
    private javax.swing.JPanel panelSession;
    private javax.swing.JPanel panelShow;
    private javax.swing.JPasswordField passField;
    private javax.swing.JButton removeButton;
    private javax.swing.JTextField removeField;
    private javax.swing.JComboBox sksCourse;
    private javax.swing.JTable tabelData;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
